"""Canonical RULER / Mood-Meter emotion lexicon (stdlib, deterministic).

Source framework: the Mood Meter (Marc Brackett & the Yale Center for
Emotional Intelligence — RULER; "Permission to Feel"). The Mood Meter
places every emotion in one of four quadrants by VALENCE (pleasant ↔
unpleasant) × ENERGY (high ↔ low):

  yellow = high energy + pleasant     green = low energy + pleasant
  red    = high energy + unpleasant   blue  = low energy + unpleasant

This module is the canonical NAME → quadrant map plus a concise,
framework-faithful one-line description per emotion. The descriptions are
our OWN neutral wording (the RULER framework is academically published;
this is NOT a copy of any app's proprietary description text). It covers
the published 100-word Mood Meter core plus the common expanded
vocabulary the source app uses (~140 entries), so the importer recognises
real logs instead of falling back to "unknown".

Keys are the canonical lowercase emotion word(s). Lookup is normalised
(lowercase, trimmed, internal whitespace collapsed) so "At Ease",
"at  ease" and "AT EASE" all resolve. Pure data + a pure lookup — no I/O,
no network, no LLM.
"""

from __future__ import annotations

# emotion → (quadrant, description). Quadrant ∈ {yellow, green, red, blue}.
EMOTIONS: dict[str, tuple[str, str]] = {
    # ---- YELLOW · high energy · pleasant -----------------------------
    "surprised": ("yellow", "jolted by something sudden and welcome"),
    "upbeat": ("yellow", "buoyant and positively energised"),
    "festive": ("yellow", "celebratory and high-spirited"),
    "exhilarated": ("yellow", "thrilled and intensely alive"),
    "ecstatic": ("yellow", "overwhelming, soaring joy"),
    "hyper": ("yellow", "restlessly over-energised"),
    "cheerful": ("yellow", "brightly and openly happy"),
    "motivated": ("yellow", "driven to act toward a goal"),
    "inspired": ("yellow", "lifted and moved to create"),
    "elated": ("yellow", "jubilant and uplifted"),
    "energized": ("yellow", "charged with active energy"),
    "lively": ("yellow", "animated and full of life"),
    "excited": ("yellow", "eager anticipation of something good"),
    "optimistic": ("yellow", "expecting things to go well"),
    "enthusiastic": ("yellow", "wholeheartedly keen"),
    "pleased": ("yellow", "satisfied and glad"),
    "focused": ("yellow", "alert and locked onto the task"),
    "happy": ("yellow", "a bright, pleasant good feeling"),
    "proud": ("yellow", "satisfied by your own worth or work"),
    "thrilled": ("yellow", "sharp burst of delighted excitement"),
    "joyful": ("yellow", "full, radiant gladness"),
    "joy": ("yellow", "full, radiant gladness"),
    "hopeful": ("yellow", "expecting and reaching for good"),
    "playful": ("yellow", "light, fun, mischievous energy"),
    "blissful": ("yellow", "perfect, serene happiness with energy"),
    "amazed": ("yellow", "struck with wonder"),
    "awe": ("yellow", "humbled wonder at something vast"),
    "curious": ("yellow", "drawn to explore and know more"),
    "eager": ("yellow", "impatiently keen to begin"),
    "engaged": ("yellow", "absorbed and actively involved"),
    "determined": ("yellow", "firmly resolved to see it through"),
    "empowered": ("yellow", "capable and in control of your power"),
    "confident": ("yellow", "sure of your ability"),
    "accomplished": ("yellow", "fulfilled by something achieved"),
    "successful": ("yellow", "having attained a desired result"),
    "alive": ("yellow", "vivid, fully present and vital"),
    "passionate": ("yellow", "intensely committed and fervent"),
    "stimulated": ("yellow", "mentally roused and engaged"),
    "wishful": ("yellow", "longing brightly for something"),
    # ---- GREEN · low energy · pleasant -------------------------------
    "at ease": ("green", "relaxed and untroubled"),
    "easygoing": ("green", "calm, tolerant, unbothered"),
    "content": ("green", "quietly satisfied with how things are"),
    "loving": ("green", "warm, tender affection toward others"),
    "fulfilled": ("green", "deeply satisfied and complete"),
    "calm": ("green", "settled and free of agitation"),
    "secure": ("green", "safe and steady, nothing to fear"),
    "satisfied": ("green", "your needs or wants are met"),
    "grateful": ("green", "thankful for something received"),
    "thankful": ("green", "thankful for something received"),
    "touched": ("green", "gently moved by kindness or meaning"),
    "relaxed": ("green", "loose, unstrained, at rest"),
    "chill": ("green", "easy, low-key, unworried"),
    "restful": ("green", "calmly recuperative"),
    "blessed": ("green", "fortunate and graced"),
    "balanced": ("green", "steady and evenly centred"),
    "mellow": ("green", "soft, gentle, low-key"),
    "thoughtful": ("green", "calmly reflective"),
    "peaceful": ("green", "deeply free of conflict"),
    "comfortable": ("green", "at ease in body and mind"),
    "carefree": ("green", "free of worry or burden"),
    "sleepy": ("green", "pleasantly drowsy"),
    "complacent": ("green", "contentedly unconcerned"),
    "tranquil": ("green", "serenely still"),
    "cozy": ("green", "warm, snug, safe-feeling"),
    "serene": ("green", "clear, untroubled calm"),
    "loved": ("green", "held in others' affection"),
    "appreciated": ("green", "valued and acknowledged"),
    "connected": ("green", "close and in tune with others"),
    "supported": ("green", "backed and held up by others"),
    "relieved": ("green", "eased after worry has passed"),
    "safe": ("green", "protected and out of danger"),
    "compassionate": ("green", "moved to care for others' pain"),
    "empathetic": ("green", "feeling with another person"),
    "humble": ("green", "modest, without inflated ego"),
    "free": ("green", "unconstrained and unburdened"),
    "nostalgic": ("green", "tender longing for the past"),
    "warm": ("green", "softly affectionate"),
    "good": ("green", "a plain, settled sense of well"),
    # ---- RED · high energy · unpleasant ------------------------------
    "enraged": ("red", "violently, explosively angry"),
    "panicked": ("red", "overtaken by sudden uncontrollable fear"),
    "stressed": ("red", "strained by too much demand"),
    "jittery": ("red", "shaky with nervous energy"),
    "shocked": ("red", "jarred by something sudden and bad"),
    "livid": ("red", "furiously, intensely angry"),
    "furious": ("red", "extremely angry"),
    "frustrated": ("red", "blocked from a goal and agitated"),
    "tense": ("red", "tight, braced, unable to relax"),
    "stunned": ("red", "shocked into momentary blankness"),
    "fuming": ("red", "smouldering with anger"),
    "frightened": ("red", "gripped by fear"),
    "afraid": ("red", "anticipating danger or harm"),
    "scared": ("red", "frightened by a perceived threat"),
    "angry": ("red", "strong displeasure at a wrong"),
    "nervous": ("red", "anxiously on edge"),
    "restless": ("red", "unable to settle or be still"),
    "anxious": ("red", "uneasy dread of a possible threat"),
    "apprehensive": ("red", "uneasy about what may come"),
    "worried": ("red", "troubled by anxious thoughts"),
    "irritated": ("red", "low-grade angry annoyance"),
    "annoyed": ("red", "mildly bothered and impatient"),
    "repulsed": ("red", "strong aversion and disgust"),
    "troubled": ("red", "disturbed and unsettled"),
    "concerned": ("red", "anxiously caring about an outcome"),
    "uneasy": ("red", "vaguely anxious, not at rest"),
    "peeved": ("red", "irritably resentful"),
    "overwhelmed": ("red", "swamped beyond what you can handle"),
    "agitated": ("red", "stirred up and unable to calm"),
    "embarrassed": ("red", "self-conscious after a misstep"),
    "pressured": ("red", "pushed by heavy expectation"),
    "jealous": ("red", "threatened over something you value"),
    "envious": ("red", "resentful of what another has"),
    "frantic": ("red", "wildly agitated and rushed"),
    "alarmed": ("red", "suddenly frightened into alertness"),
    "defensive": ("red", "guarded and braced against attack"),
    "hostile": ("red", "antagonistic and confrontational"),
    "resentful": ("red", "bitter over a perceived wrong"),
    "irate": ("red", "sharply, openly angry"),
    "disturbed": ("red", "unsettled and distressed"),
    "disgusted": ("red", "repelled by something offensive"),
    "contempt": ("red", "scornful disdain for someone"),
    "conflicted": ("red", "torn between opposing pulls"),
    "shaken": ("red", "rattled and destabilised"),
    "exasperated": ("red", "worn thin to the edge of anger"),
    # ---- BLUE · low energy · unpleasant ------------------------------
    "glum": ("blue", "quietly low and sullen"),
    "disappointed": ("blue", "let down by an unmet hope"),
    "down": ("blue", "low-spirited and flat"),
    "apathetic": ("blue", "without interest, care or drive"),
    "pessimistic": ("blue", "expecting the worst"),
    "morose": ("blue", "gloomily sullen"),
    "discouraged": ("blue", "drained of hope or confidence"),
    "sad": ("blue", "unhappy over a loss or lack"),
    "bored": ("blue", "listless from lack of interest"),
    "fatigued": ("blue", "low-energy weariness"),
    "tired": ("blue", "in need of rest; depleted"),
    "despondent": ("blue", "deeply dejected and low"),
    "depressed": ("blue", "heavy, persistent low mood"),
    "sullen": ("blue", "silently resentful and gloomy"),
    "exhausted": ("blue", "completely drained of energy"),
    "spent": ("blue", "used up; nothing left"),
    "drained": ("blue", "emptied of energy"),
    "hopeless": ("blue", "without any expectation of better"),
    "lonely": ("blue", "painfully disconnected from others"),
    "disheartened": ("blue", "discouraged and dispirited"),
    "miserable": ("blue", "deeply, wretchedly unhappy"),
    "desolate": ("blue", "bleakly empty and alone"),
    "numb": ("blue", "emotionally flat and unfeeling"),
    "bummed": ("blue", "mildly let down and low"),
    "disengaged": ("blue", "checked out and uninvolved"),
    "ashamed": ("blue", "painfully aware of a personal failing"),
    "guilty": ("blue", "weighed by having done wrong"),
    "regretful": ("blue", "sorry over a past choice"),
    "remorseful": ("blue", "deeply sorry for harm done"),
    "insecure": ("blue", "uncertain of your own worth"),
    "vulnerable": ("blue", "exposed and easily hurt"),
    "helpless": ("blue", "unable to change a bad situation"),
    "powerless": ("blue", "stripped of any control"),
    "defeated": ("blue", "beaten and out of fight"),
    "worthless": ("blue", "feeling of having no value"),
    "heartbroken": ("blue", "crushed by grief or loss"),
    "wistful": ("blue", "softly sad with longing"),
    "melancholy": ("blue", "pensive, lingering sadness"),
    "grief": ("blue", "deep sorrow from loss"),
    "lost": ("blue", "without direction or anchor"),
    "withdrawn": ("blue", "pulled away and shut in"),
    "fragile": ("blue", "easily broken or overwhelmed"),
    "burned out": ("blue", "depleted by prolonged stress"),
    "gloomy": ("blue", "darkly low and dim"),
    "blah": ("blue", "flat, indifferent, low"),
    # ---- expanded vocabulary the source app also offers --------------
    "productive": ("yellow", "energised by getting things done"),
    "challenged": ("yellow", "engaged and stretched by a demand"),
    "stuck": ("red", "blocked and unable to move forward"),
    "distracted": ("red", "scattered and unable to focus"),
    "indecisive": ("red", "uneasily unable to decide"),
    "pissed": ("red", "sharply angry"),
    "mad": ("red", "angry and provoked"),
    "meh": ("blue", "indifferent and unmoved"),
    "lovesick": ("blue", "aching with longing for someone"),
    "disconnected": ("blue", "detached and out of touch"),
    "empty": ("blue", "hollow and without feeling"),
    "painful": ("blue", "hurting and weighed down"),
    "blue": ("blue", "low-spirited and sad"),
    "groggy": ("blue", "foggy and sluggish"),
}


def normalize(name: str) -> str:
    """Lowercase, strip, collapse internal whitespace — the lookup key."""
    return " ".join((name or "").strip().lower().split())


def lookup(name: str) -> tuple[str, str] | None:
    """(quadrant, description) for an emotion, or None if not in the
    lexicon. Pure, deterministic, case/space-insensitive."""
    return EMOTIONS.get(normalize(name))
